dist: trusty
sudo: false
language: node_js

matrix:
  include:
    - node_js: "node"

addons:
  chrome: stable

notifications:
  email:
    on_failure: always

branches:
  only:
    - /.*/

install:
  - npm install

before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
  - npm run tsc
  - npm run build:prod
  - node server.js &
  - sleep 3

script:
  - npm run lint
  - npm run test -- test/unit/
  - npm run test -- test/integration/
  - npm run test -- test/e2e/